### ISSUE TITLE
Docker GPU Error

### ISSUE THREAD

**Issue by KosarKeshavarz** [HaoLiuHust/GroundingDINO-Service#1]
I come across the error below after running the image for creating .mar file:
WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use the NVIDIA Container Toolkit to start this container with GPU support; see
   https://docs.nvidia.com/datacenter/cloud-native/ .''
   
   i'm serving it on a remote VM . I checked Nvidia-smi and everything looks fine(torch is able to recognize the gpus)
   using ubuntu22 and cuda11.7

  do you have any solutions for this problem?

**Comment by HaoLiuHust** [comment]
did you installed nvidia-docker-runtime? or have you tired start docker with --gpus=all flag?

**Comment by KosarKeshavarz** [comment]
> did you installed nvidia-docker-runtime? or have you tired start docker with --gpus=all flag?

actually, something was wrong with Nvidia-container-toolkit. the problem is solved. thank you

**Comment by HaoLiuHust** [comment]
glad to hear that
